import { Request, Response } from 'express';
import { z } from 'zod';
import { prisma } from '../config/prisma';
import { ApiError } from '../utils/ApiError';
import { startDocument, drawField, drawTable, drawTotal, drawFooterNote, finishDocument, formatNaira } from '../utils/pdf';
import { isMedicationArray, toNumber, isOrderItemArray } from '../utils/typeGuards';
import { Medication, OrderItem } from './types';

/** Looks up the PatientProfile row for the logged-in user, or throws. */
async function getPatientProfile(userId: string) {
  const profile = await prisma.patientProfile.findUnique({ where: { userId } });
  if (!profile) throw ApiError.notFound('Patient profile not found');
  return profile;
}

// ---------- Profile ----------

export async function getProfile(req: Request, res: Response): Promise<void> {
  const profile = await prisma.patientProfile.findUnique({
    where: { userId: req.user!.userId },
    include: { user: { select: { id: true, name: true, email: true, phone: true, avatarUrl: true } } },
  });
  if (!profile) throw ApiError.notFound('Patient profile not found');
  res.json(profile);
}

const updateProfileSchema = z.object({
  dateOfBirth: z.string().datetime().optional(),
  bloodType: z.string().optional(),
  genotype: z.string().optional(),
  nhisNumber: z.string().optional(),
  allergies: z.string().optional(),
  address: z.string().optional(),
  emergencyContact: z.string().optional(),
  emergencyPhone: z.string().optional(),
});

export async function updateProfile(req: Request, res: Response): Promise<void> {
  const data = updateProfileSchema.parse(req.body);
  const patient = await getPatientProfile(req.user!.userId);
  const updated = await prisma.patientProfile.update({
    where: { id: patient.id },
    data: { ...data, dateOfBirth: data.dateOfBirth ? new Date(data.dateOfBirth) : undefined },
  });
  res.json(updated);
}

// ---------- Pharmacy orders ----------

const createOrderSchema = z.object({
  pharmacyId: z.string(),
  prescriptionId: z.string().optional(),
  items: z.array(z.object({ inventoryId: z.string(), name: z.string(), qty: z.number().min(1), price: z.number() })),
});

export async function listOrders(req: Request, res: Response): Promise<void> {
  const patient = await getPatientProfile(req.user!.userId);
  const orders = await prisma.pharmacyOrder.findMany({
    where: { patientId: patient.id },
    include: { pharmacy: { include: { user: { select: { name: true } } } } },
    orderBy: { createdAt: 'desc' },
  });
  res.json(orders);
}

export async function createOrder(req: Request, res: Response): Promise<void> {
  const data = createOrderSchema.parse(req.body);
  const patient = await getPatientProfile(req.user!.userId);
  const total = data.items.reduce((sum, i) => sum + i.qty * i.price, 0);

  // Decrement stock and create the order atomically so two patients can't both
  // "buy" the last unit of something out from under each other.
  const order = await prisma.$transaction(async (tx) => {
    for (const item of data.items) {
      const updated = await tx.inventory.updateMany({
        where: { id: item.inventoryId, stock: { gte: item.qty } },
        data: { stock: { decrement: item.qty } },
      });
      if (updated.count === 0) {
        throw ApiError.conflict(`Not enough stock for ${item.name}`);
      }
    }
    return tx.pharmacyOrder.create({
      data: {
        patientId: patient.id,
        pharmacyId: data.pharmacyId,
        prescriptionId: data.prescriptionId,
        items: data.items,
        total,
      },
    });
  });

  res.status(201).json(order);
}

export async function getOrderInvoicePdf(req: Request, res: Response): Promise<void> {
  const patient = await getPatientProfile(req.user!.userId);
  const order = await prisma.pharmacyOrder.findUnique({
    where: { id: req.params.id },
    include: { pharmacy: { select: { pharmacyName: true } }, patient: { include: { user: { select: { name: true } } } } },
  });
  if (!order || order.patientId !== patient.id) throw ApiError.notFound('Order not found');

  // Use type guard to safely narrow Prisma Json field
  if (!isOrderItemArray(order.items)) {
    throw ApiError.badRequest('Invalid order items structure');
  }
  const items: OrderItem[] = order.items;

  const h = await startDocument('Invoice', `Order #${order.id.slice(0, 8)}`);
  drawField(h, 'Patient', order.patient.user.name);
  drawField(h, 'Pharmacy', order.pharmacy.pharmacyName);
  drawField(h, 'Date', order.createdAt.toLocaleString());
  drawField(h, 'Status', order.status.replace(/_/g, ' '));
  drawTable(
    h,
    items.map((i) => ({ name: i.name, qty: String(i.qty), amount: formatNaira(i.qty * i.price) }))
  );
  drawTotal(h, 'Total', formatNaira(toNumber(order.total)));
  drawFooterNote(h, 'This invoice was generated by N-Health for a pharmacy order.');

  const pdf = await finishDocument(h);
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="invoice-${order.id.slice(0, 8)}.pdf"`);
  res.send(pdf);
}

// ---------- Prescriptions (read-only for patient) ----------

export async function listPrescriptions(req: Request, res: Response): Promise<void> {
  const patient = await getPatientProfile(req.user!.userId);
  const prescriptions = await prisma.prescription.findMany({
    where: { patientId: patient.id },
    include: { doctor: { include: { user: { select: { name: true } } } } },
    orderBy: { issuedAt: 'desc' },
  });
  res.json(prescriptions);
}

export async function getPrescriptionPdf(req: Request, res: Response): Promise<void> {
  const patient = await getPatientProfile(req.user!.userId);
  const prescription = await prisma.prescription.findUnique({
    where: { id: req.params.id },
    include: {
      doctor: { include: { user: { select: { name: true } } } },
      patient: { include: { user: { select: { name: true } } } },
    },
  });
  if (!prescription || prescription.patientId !== patient.id) throw ApiError.notFound('Prescription not found');

  // Use type guard for safe type narrowing
  if (!isMedicationArray(prescription.medications)) {
    throw ApiError.badRequest('Invalid prescription medications structure');
  }
  const meds: Medication[] = prescription.medications;

  const h = await startDocument('Prescription', `Issued ${prescription.issuedAt.toLocaleDateString()}`);
  drawField(h, 'Patient', prescription.patient.user.name);
  drawField(h, 'Prescribed by', `Dr. ${prescription.doctor.user.name}`);
  drawTable(
    h,
    meds.map((m) => ({ name: m.name, qty: m.dosage, amount: `${m.frequency}, ${m.durationDays}d` })),
    { name: 'MEDICATION', qty: 'DOSAGE', amount: 'SCHEDULE' }
  );
  drawFooterNote(h, 'This prescription was issued via N-Health. Present it at any partner pharmacy.');

  const pdf = await finishDocument(h);
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="prescription-${prescription.id.slice(0, 8)}.pdf"`);
  res.send(pdf);
}
